"""
dashboard/area_detail.py
=========================
Area drill-down panel.
Shows: factor scores, WSI/WEI cards, radar chart, trend chart,
       and rule-based policy suggestions.
"""

from __future__ import annotations
import streamlit as st
import pandas as pd

from config import FACTOR_LABELS, FACTOR_COLORS
from policy_engine.rules import get_suggestions, format_suggestions_markdown
from dashboard.charts import area_radar, mci_trend_line


def _score_color(val: float) -> str:
    if val < 25:   return "#E24B4A"
    elif val < 45: return "#EF9F27"
    elif val < 60: return "#378ADD"
    elif val < 75: return "#639922"
    return "#1D9E75"


def _factor_bar(label: str, val: float, color: str):
    pct = int(max(0, min(100, val)))
    st.markdown(
        f"<div style='margin-bottom:8px'>"
        f"<div style='font-size:12px;color:var(--text-color,gray);margin-bottom:2px'>"
        f"{label}: <b style='color:{color}'>{val:.1f}</b></div>"
        f"<div style='background:#e8e8e8;border-radius:4px;height:7px'>"
        f"<div style='background:{color};width:{pct}%;height:100%;border-radius:4px'></div>"
        f"</div></div>",
        unsafe_allow_html=True,
    )


def render_area_detail(
    area_row: dict,
    sub_df: pd.DataFrame,
    timeseries_df: pd.DataFrame,
):
    """
    Renders the complete drill-down panel for a selected area.

    Parameters:
        area_row:      dict of score values for the area (from mci_scores)
        sub_df:        factor_subcomponent_scores dataframe
        timeseries_df: mci_timeseries_scores dataframe (all years)
    """
    city  = area_row.get("city", "")
    area  = area_row.get("area", "")
    tier  = area_row.get("city_tier", area_row.get("area_type", ""))
    mci   = area_row.get("MCI", 0)
    cls   = area_row.get("MCI_class", "")

    st.markdown(f"### {area}, {city}")
    st.caption(f"{tier}  ·  MCI = **{mci:.1f}**  ·  {cls}")

    col1, col2, col3 = st.columns([1.1, 1.1, 1.8])

    # ── Col 1: Factor score bars ─────────────────────────────────────────────
    with col1:
        st.markdown("**Factor scores**")
        for key, label in FACTOR_LABELS.items():
            val = area_row.get(key, 0)
            _factor_bar(label, val, _score_color(val))

        st.markdown(f"**Cluster:** {area_row.get('cluster_label','—')}")
        if area_row.get("Profile_label"):
            st.caption(area_row["Profile_label"])

    # ── Col 2: WSI / WEI cards ───────────────────────────────────────────────
    with col2:
        st.markdown("**Women impact**")
        for score_key, label, risk_key in [
            ("WSI", "Women Safety Index",     "Safety_risk"),
            ("WEI", "Women Employment Index", "Employment_gap"),
        ]:
            val  = area_row.get(score_key, 0)
            risk = area_row.get(risk_key, "")
            col  = _score_color(val)
            st.markdown(
                f"<div style='padding:10px 12px;border-radius:8px;"
                f"border:1px solid {col}30;background:{col}08;margin-bottom:10px'>"
                f"<div style='font-size:11px;color:{col}'>{label} ({score_key})</div>"
                f"<div style='font-size:26px;font-weight:600;color:{col}'>{val:.1f}</div>"
                f"<div style='font-size:11px;color:gray'>{risk}</div>"
                f"</div>",
                unsafe_allow_html=True,
            )

    # ── Col 3: Radar chart ───────────────────────────────────────────────────
    with col3:
        st.markdown("**Sub-component radar**")
        fig_radar = area_radar(area_row, sub_df)
        st.plotly_chart(fig_radar, use_container_width=True)

    # ── Trend chart ──────────────────────────────────────────────────────────
    trend = timeseries_df[
        (timeseries_df["city"] == city) &
        (timeseries_df["area"] == area)
    ]
    if len(trend) > 1:
        st.markdown("**Historical trend**")
        fig_trend = mci_trend_line(trend, f"{area}, {city}")
        st.plotly_chart(fig_trend, use_container_width=True)

    # ── Rule-based policy suggestions ────────────────────────────────────────
    st.markdown("---")
    st.markdown("#### Recommended interventions")
    st.caption("Generated by the rule-based policy engine from factor scores")

    suggestions = get_suggestions(area_row, n=3)
    if suggestions:
        for s in suggestions:
            icons = {1: "🔴", 2: "🟡", 3: "🟢"}
            cat_icons = {
                "IFS": "📡", "DLS": "💻", "SES": "🏛️",
                "WDI": "👩", "WSI": "🛡️", "WEI": "💼",
            }
            with st.expander(
                f"{icons.get(s.priority,'⚪')} {s.short_title} {cat_icons.get(s.category,'')}",
                expanded=(s.priority == 1),
            ):
                st.markdown(s.action)
                st.caption(f"Rationale: {s.rationale}")
                if s.scheme_or_program:
                    st.markdown(f"📋 **Scheme / Programme:** {s.scheme_or_program}")
    else:
        st.success("No critical interventions triggered — area is performing adequately.")